/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package practical13;

/**
 *
 * @author ASUS
 */
public class Practical13_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Practical13_GUI
     */
    public Practical13_GUI() {
        initComponents();
        // Initialize combo box with characters
        for (char c = 'a'; c <= 'z'; c++) {
            ComboBox.addItem(String.valueOf(c));
        }
        for (char c = 'A'; c <= 'Z'; c++) {
            ComboBox.addItem(String.valueOf(c));
        }
        for (char c = '0'; c <= '9'; c++) {
            ComboBox.addItem(String.valueOf(c));
        }
        ComboBox.addItem(" ");
        ComboBox.addItem("\t");
        ComboBox.addItem("\n");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        TextAnalyzerTittle = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        TextEnter = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Screen = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        EnterShift3 = new javax.swing.JTextField();
        EnterShift4 = new javax.swing.JTextField();
        EnterShift2 = new javax.swing.JTextField();
        EnterShift = new javax.swing.JTextField();
        EnterNumber = new javax.swing.JTextField();
        Length = new javax.swing.JTextField();
        Lines = new javax.swing.JTextField();
        Tabs = new javax.swing.JTextField();
        Space = new javax.swing.JTextField();
        Words = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        EnterShift11 = new javax.swing.JTextField();
        EnterShift12 = new javax.swing.JTextField();
        EnterNumber2 = new javax.swing.JTextField();
        ComboBox = new javax.swing.JComboBox<>();
        SpecificWord = new javax.swing.JTextField();
        WordEnter = new javax.swing.JButton();
        EnterNumber3 = new javax.swing.JTextField();
        CharacterCount = new javax.swing.JTextField();
        WordCount = new javax.swing.JTextField();
        EnterForCharacterCount = new javax.swing.JButton();

        jScrollPane2.setViewportView(jTextPane1);

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(4, 134, 134));

        TextAnalyzerTittle.setEditable(false);
        TextAnalyzerTittle.setBackground(new java.awt.Color(0, 153, 153));
        TextAnalyzerTittle.setFont(new java.awt.Font("STZhongsong", 1, 32)); // NOI18N
        TextAnalyzerTittle.setForeground(new java.awt.Color(255, 255, 255));
        TextAnalyzerTittle.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextAnalyzerTittle.setText("Text Analyzer");
        TextAnalyzerTittle.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TextAnalyzerTittle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextAnalyzerTittleActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(88, 173, 173));

        TextEnter.setBackground(new java.awt.Color(0, 153, 153));
        TextEnter.setForeground(new java.awt.Color(255, 255, 255));
        TextEnter.setText("Enter");
        TextEnter.setToolTipText("Enter to submit ");
        TextEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextEnterActionPerformed(evt);
            }
        });

        Screen.setBackground(new java.awt.Color(0, 153, 153));
        Screen.setColumns(20);
        Screen.setForeground(new java.awt.Color(255, 255, 255));
        Screen.setLineWrap(true);
        Screen.setRows(5);
        Screen.setWrapStyleWord(true);
        jScrollPane1.setViewportView(Screen);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(TextEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );

        jPanel3.setBackground(new java.awt.Color(88, 173, 173));

        EnterShift3.setBackground(new java.awt.Color(0, 153, 153));
        EnterShift3.setForeground(new java.awt.Color(255, 255, 255));
        EnterShift3.setText("No. of Spaces -");
        EnterShift3.setToolTipText("Enter the shift value");
        EnterShift3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterShift3ActionPerformed(evt);
            }
        });

        EnterShift4.setBackground(new java.awt.Color(0, 153, 153));
        EnterShift4.setForeground(new java.awt.Color(255, 255, 255));
        EnterShift4.setText("No. of Words -");
        EnterShift4.setToolTipText("Enter the shift value");

        EnterShift2.setBackground(new java.awt.Color(0, 153, 153));
        EnterShift2.setForeground(new java.awt.Color(255, 255, 255));
        EnterShift2.setText("No. of Tabs -");
        EnterShift2.setToolTipText("Enter the shift value");

        EnterShift.setBackground(new java.awt.Color(0, 153, 153));
        EnterShift.setForeground(new java.awt.Color(255, 255, 255));
        EnterShift.setText("No. of Lines -");
        EnterShift.setToolTipText("Enter the shift value");

        EnterNumber.setBackground(new java.awt.Color(0, 153, 153));
        EnterNumber.setForeground(new java.awt.Color(255, 255, 255));
        EnterNumber.setText("Length of Text  -");
        EnterNumber.setToolTipText("Enter the number");
        EnterNumber.setAutoscrolls(false);

        Space.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpaceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(EnterShift3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EnterShift2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EnterShift, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EnterNumber, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EnterShift4))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Length, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lines, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Space, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Words, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Length)
                    .addComponent(EnterNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lines)
                    .addComponent(EnterShift))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Tabs, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(EnterShift2))
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Space, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 5, Short.MAX_VALUE))
                    .addComponent(EnterShift3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EnterShift4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Words, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addGap(9, 9, 9))
        );

        jPanel5.setBackground(new java.awt.Color(88, 173, 173));

        EnterShift11.setBackground(new java.awt.Color(0, 153, 153));
        EnterShift11.setForeground(new java.awt.Color(255, 255, 255));
        EnterShift11.setText("Word Count is -");
        EnterShift11.setToolTipText("Enter the shift value");

        EnterShift12.setBackground(new java.awt.Color(0, 153, 153));
        EnterShift12.setForeground(new java.awt.Color(255, 255, 255));
        EnterShift12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EnterShift12.setText("Specific Word Count");
        EnterShift12.setToolTipText("Enter the shift value");

        EnterNumber2.setBackground(new java.awt.Color(0, 153, 153));
        EnterNumber2.setForeground(new java.awt.Color(255, 255, 255));
        EnterNumber2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EnterNumber2.setText("Specific Character Count");
        EnterNumber2.setToolTipText("Enter the number");
        EnterNumber2.setAutoscrolls(false);

        SpecificWord.setText("Enter Word here");

        WordEnter.setBackground(new java.awt.Color(0, 153, 153));
        WordEnter.setForeground(new java.awt.Color(255, 255, 255));
        WordEnter.setText("Enter");
        WordEnter.setToolTipText("Enter to submit ");
        WordEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WordEnterActionPerformed(evt);
            }
        });

        EnterNumber3.setBackground(new java.awt.Color(0, 153, 153));
        EnterNumber3.setForeground(new java.awt.Color(255, 255, 255));
        EnterNumber3.setText("Chracter Count is -");
        EnterNumber3.setToolTipText("Enter the number");
        EnterNumber3.setAutoscrolls(false);

        EnterForCharacterCount.setBackground(new java.awt.Color(0, 153, 153));
        EnterForCharacterCount.setForeground(new java.awt.Color(255, 255, 255));
        EnterForCharacterCount.setText("Enter to See Count");
        EnterForCharacterCount.setToolTipText("Enter to submit ");
        EnterForCharacterCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterForCharacterCountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(EnterForCharacterCount, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CharacterCount, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(EnterNumber3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(SpecificWord, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(WordEnter, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                        .addComponent(ComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                            .addComponent(EnterShift11, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(WordCount, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(EnterShift12, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(EnterNumber2, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(EnterNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(EnterNumber3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CharacterCount, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EnterForCharacterCount, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(EnterShift12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SpecificWord, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WordEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(EnterShift11, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(WordCount))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(TextAnalyzerTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(TextAnalyzerTittle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void analyzeText() {
    String text = Screen.getText();
    Practical13 analyzer = new Practical13(text);
    
    // Update basic statistics
    Length.setText(String.valueOf(analyzer.getTextLength()));
    Lines.setText(String.valueOf(analyzer.getLineCount()));
    Tabs.setText(String.valueOf(analyzer.getTabCount()));
    Space.setText(String.valueOf(analyzer.getSpaceCount()));
    Words.setText(String.valueOf(analyzer.getWordCount()));
    
    // Clear character count until button is pressed
    CharacterCount.setText("");
}
    private void TextAnalyzerTittleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextAnalyzerTittleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextAnalyzerTittleActionPerformed

    private void TextEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextEnterActionPerformed
        analyzeText();
    }//GEN-LAST:event_TextEnterActionPerformed

    private void EnterShift3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterShift3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnterShift3ActionPerformed

    private void WordEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WordEnterActionPerformed
    analyzeText(); // This will update basic stats and clear character count
    String word = SpecificWord.getText();
    if (!word.isEmpty()) {
        Practical13 analyzer = new Practical13(Screen.getText());
        int count = analyzer.getWordCount(word);
        WordCount.setText(String.valueOf(count));
    }
    }//GEN-LAST:event_WordEnterActionPerformed

    private void SpaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SpaceActionPerformed

    private void EnterForCharacterCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterForCharacterCountActionPerformed
    String text = Screen.getText();
    if (!text.isEmpty()) {
        String selectedChar = (String)ComboBox.getSelectedItem();
        if (selectedChar != null && !selectedChar.isEmpty()) {
            Practical13 analyzer = new Practical13(text);
            int charCount = analyzer.getCharCount(selectedChar.charAt(0));
            CharacterCount.setText(String.valueOf(charCount));
        }
    }
    }//GEN-LAST:event_EnterForCharacterCountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Practical13_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Practical13_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Practical13_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Practical13_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Practical13_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CharacterCount;
    private javax.swing.JComboBox<String> ComboBox;
    private javax.swing.JButton EnterForCharacterCount;
    private javax.swing.JTextField EnterNumber;
    private javax.swing.JTextField EnterNumber2;
    private javax.swing.JTextField EnterNumber3;
    private javax.swing.JTextField EnterShift;
    private javax.swing.JTextField EnterShift11;
    private javax.swing.JTextField EnterShift12;
    private javax.swing.JTextField EnterShift2;
    private javax.swing.JTextField EnterShift3;
    private javax.swing.JTextField EnterShift4;
    private javax.swing.JTextField Length;
    private javax.swing.JTextField Lines;
    private javax.swing.JTextArea Screen;
    private javax.swing.JTextField Space;
    private javax.swing.JTextField SpecificWord;
    private javax.swing.JTextField Tabs;
    private javax.swing.JTextField TextAnalyzerTittle;
    private javax.swing.JButton TextEnter;
    private javax.swing.JTextField WordCount;
    private javax.swing.JButton WordEnter;
    private javax.swing.JTextField Words;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
